### ISSUE TITLE
Placeholders in social items appear twice

### ISSUE THREAD

**Issue by pysailor** [ploneintranet/ploneintranet.theme#82]
The default placeholder on items in the social stream is "Leave a comment". The placeholder (on the dashboard) for the box to write a new comment is "Post a message".
However, when loading the dashboard (proto), both messages appear on top of each other in all items if the stream:
![screen shot 2015-02-15 at 17 17 39](https://cloud.githubusercontent.com/assets/642660/6203862/ae743ac6-b536-11e4-8b57-8d31f640cfa6.png)
(The placeholder attribute of the textarea circled red above reads "Leave a comment", i.e. "Post a message" comes from somewhere else.)

Once I post a message, it seems OK at first glance, but only because the 2 placeholders are identical:
![screen shot 2015-02-15 at 17 19 37](https://cloud.githubusercontent.com/assets/642660/6203866/e9d73e74-b536-11e4-932b-e6aef645af43.png)
If I use the Inspector to change the placeholder of the textarea, you can see the 2 different placeholders:
![screen shot 2015-02-15 at 17 20 06](https://cloud.githubusercontent.com/assets/642660/6203872/19736efa-b537-11e4-9aac-c113894c1a57.png)

Some "magic" seems to happen that pulls the placeholder text not only from the "placehoder" attribute, but a second location.

I noticed this when I transferred the latest markup to the plonesocial code, where this bug also appears. Could it be related to 04d0651047f8a73dac5697623674c5e88ee88772 (change from pat-updatesocial to pat-content-mirror)?

**Comment by cornae** [comment]
Looks like a regression in pat-content mirror without having had a thorough look. Did it drop out of the bundle?

Verstuurd vanaf mijn iPad

**Comment by pysailor** [comment]
Cornelis G. A. Kolbach wrote on 15/02/15 17:31:
> Looks like a regression in pat-content mirror without having had a
> thorough look. Did it drop out of the bundle?
I checked, pat-content-mirror is still part of the bundle.

**Comment by fulv** [comment]
@pysailor:
> Could it be related to 04d0651 (change from pat-updatesocial to pat-content-mirror)?

No, I doubt that would cause a problem.  Just for context, pat-updatesocial was a very short-lived pattern that only existed for a couple of weeks at most.  Then someone felt the name was not descriptive enough and asked for it to be given a more appropriate name, before it gained any usage, so I scrapped pat-updatesocial and created pat-content-mirror instead, for exactly the same pattern.

Customizing the placeholder is something that should have been fixed in https://github.com/ploneintranet/pat-content-mirror/commit/10896a28fabc1e13507574439c983f11ebe2312f and https://github.com/ploneintranet/pat-content-mirror/commit/095468e41f239f82acecc56a1728197eddc97c35

**Comment by pysailor** [comment]
Hi @fulv,

thanks for the explanations. I'll try to install pat-content-mirror stand-alone (following the instructions at http://docs.ploneintranet.org/development/patterns.html#setting-up-a-standalone-build), to see if I can get this bug in isolation.
In ploneintranet.theme, even after `make clean` and `make`, the bug is still there.

**Comment by pysailor** [comment]
Ok, the demo/index.html of pat-content-mirror stand-alone is working fine. But in that demo, the pattern is used only once. In PloneIntranet, we have multiple pat-content-mirror in a single page.

I  added a 2nd pat-content-mirror to the demo in this branch: https://github.com/ploneintranet/pat-content-mirror/commit/89e0010b71ed8f3daafe29e059005a714e7818c8
Regardless of which of the 2 texareas I use for typing, the text that gets mirrored always appears above the first textarea, so this might be a hint about an isolation problem (or, my selectors are wrong?).

**Comment by pysailor** [comment]
I think I might have found the solution: b74c6ac6a0a807d47e0cf914e242f3efb048f152
We can simply remove the manual insertion of the placeholder it seems, since now the placeholder attribute is being used to generate the placeholder

**Comment by pysailor** [comment]
@fulv  do you think my assumption above is valid?

**Comment by adrianwhite** [comment]
@pysailor @cornae what do you think of my comment on b74c6ac ?

**Comment by adrianwhite** [comment]
I'll take this on @pysailor.

**Comment by adrianwhite** [comment]
I don't think the placeholder appearing twice is an issue.  As @cornae says it should be the same text exactly replicated underneath and the css making it match up. I think the placeholder text could be made transparent to ensure this is the case but uif we had done that we would not have seen the the wrong placeholder text is being shown.

I think the cause of the wrong placeholder text may be pat-content-mirror but I have not had time to fully investigate. But, I think it may be because pat-content-mirror updates all the placeholders on the page not the just one being interacted with.

I'll investigate and post an issue on pat-content-mirror if this is the case.

**Comment by fulv** [comment]
I've committed my fix:
https://github.com/ploneintranet/pat-content-mirror/commit/b9c64d7a858b52f91c38b7ee62a58d869d5ac87c

**Comment by cornae** [comment]
Works :)
